name: 🐞 NextGenGUI Bug
description: File a bug/issue
title: "KCi NextGenGUI Bug Submit Form"
labels: [bug, help wanted]
assignees:
  - davekfci
  - JingtianLi-KCi
  - AaronOcchipintiKCi
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: There is no customer sensitive data in this bug report!
    description: ENSURE THERE IS NO CUSTOMER SENSITIVE DATA IN THIS BUG REPORT. THIS ISSUE IS PUBLICLY VIEWABLE AND SEARCHABLE DUE TO GITHUB'S POLICY OF NOT ALLOWING PRIVATE BUG REPORTING. IF THERE IS CUSTOMER SENSITIVE DATA PLEASE SEND VIA DIRECT EMAIL.
    options:
    - label: I AM 100% SURE THERE IS NO CUSTOMER SENSITIVE DATA!!!
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Version
    description: What version of our software are you running?
    options:
      - 0.1.28 (Default)
      - 0.1.28
      - 0.1.27
      - 0.1.26
      - 0.1.25
      - 0.1.24
      - 0.1.23
      - 0.1.22
      - 0.1.21
      - 0.1.20
      - 0.1.19
      - 0.1.18
      - 0.1.17
      - 0.1.16
      - 0.1.15
      - 0.1.14
      - 0.1.13
      - 0.1.12
      - 0.1.11
      - 0.1.10
      - 0.1.09
  validations:
    required: true
- type: dropdown
  id: Configuration
  attributes:
    label: What is the system configured as?
    multiple: false
    options:
      - Server
      - Client
      - Server/Client
- type: dropdown
  id: OS
  attributes:
    label: What Operating System are you seeing the problem on?
    multiple: true
    options:
      - Windows 10
      - Windows 7
      - Windows 11
  validations:
    required: true
- type: dropdown
  id: SQL_Version
  attributes:
    label: What SQL Version are you seeing the problem on?
    multiple: true
    options:
      - "2022"
      - "2019"
      - "2017"
      - "2016"
      - "2014"
      - "2012"
      - "2008"
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: textarea
  attributes:
    label: Anything else? Attach Files Here By Dragging Below.
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Double check that there is no customer sensitive data in this bug report!
    description: ENSURE THERE IS NO CUSTOMER SENSITIVE DATA IN THIS BUG REPORT. THIS ISSUE IS PUBLICLY VIEWABLE AND SEARCHABLE DUE TO GITHUB'S POLICY OF NOT ALLOWING PRIVATE BUG REPORTING. IF THERE IS CUSTOMER SENSITIVE DATA PLEASE SEND VIA DIRECT EMAIL.
    options:
    - label: I AM 200% SURE THERE IS NO CUSTOMER SENSITIVE DATA!!!
      required: true
